### ISSUE TITLE
Does not handle 64K devices in bsl_getInfo()

### ISSUE THREAD

**Issue by basilhussain** [gicking/stm8gal#19] opened 2020-12-11 15:05 UTC
The `bsl_getInfo()` function in bootloader.c attempts to determine memory size of the device by reading from the last byte of flash. I notice that it does not have a case for 64K devices. I believe this will mis-classify some 64K devices as having 32K of flash memory and being 'medium density' devices, when they should be 'high density'.

For example, the STM8AF5288 is a 64K device and is classified as 'high density'. See Table 1 (pg. 6) of UM0560. [ST's website product page](https://www.st.com/en/microcontrollers-microprocessors/stm8af5288.html) also says this: "_They are referred to as high density STM8A devices in STM8S series and STM8AF series 8-bit microcontrollers reference manual (RM0016)_".

I think this will lead to stm8gal incorrectly erroring with an "unsupported device" message, when in fact it should install the RAM routines for a 128K device (further evidenced by the ROM BL of a STM8AF5288 being byte-for-byte identical to a STM8S208).

**Comment by gicking** [comment] 2020-12-11 16:53
I believe there is no issue with this approach. Reason is that the 64kB 
device is only a test option of the 128kB device, i.e. they use the same 
chip internally. Consequently a read to >64kB should succeed and the 
128kB RAM routine is correctly used.

However, I haven't tested it yet. But I have a "STM8A Discovery" board 
available which uses a STM8AF5288 (64kB). It seems like I need a 
USB<->LIN adapter for serial communication, so that may take a bit...

Having said that, I also don't like the way how stm8gal detects the STM8 
variant and memory size by reading from certain addresses and checking 
for error. But it's the only method I could come up with. If anyone 
knows e.g. a secret flash address which contains the device type, I 
would gladly use that instead...



Am 11.12.20 um 16:05 schrieb Basil Hussain:

**Comment by basilhussain** [comment] 2020-12-11 18:13
Hmm, that does seem a bit 'dangerous' (for want of a better word) to assume that a read from >64KB will work successfully and result in the device being classified as high density. Who knows if in future that ST may change the behaviour of the chip, and reads past the 'official' end of flash fails?

Having had our separate discussion about the 1-byte 'patch' RAM erase/write bootloader routine for low-density STM8L devices, I also think this same issue may potentially pose a problem for such devices with less than 8K. There are some 4K devices - for example, the STM8L151G2. stm8gal might falsely declare "unsupported device" if it doesn't get the `bsl_getInfo()` check right for these.

**Comment by MarkStokes71** [comment] 2020-12-28 15:32
For what it's worth, I do have confirmation from ST Micro that devices 32k, 64k, and 128k have the same die.  The only difference is the testing.  128k devices being tested for the entire memory size.  So, the declaration of a 64k device as a 128k device for the purpose of loading the correct image is accurate (Also verified w/ STMicro).  There is information available in some "secret" locations that will absolutely determine which size is validated, but that requires an NDA.  I have seen it, so I know it exists, but being under an NDA, I cannot divulge the details of how it works.

**Comment by gicking** [comment] 2021-01-09 20:27
@Mark: I believe your ST contact mixed something up: the STM8S "medium density" (16kB, 32kB) and "high density" (64kB, 128kB) definitely have separate dies. However, the 64kB and 128kB chips have the same dies, just tested differently. This was confirmed by ST support, and also by the fact that stm8gal can write and read up to 128kB to/from a "64kB device"

So here's the picture:
  - STM8S and STM8AF use the same die, but are tested differently
  - STM8L and STM8AL use the same die, but are tested differently
  - STM8S/AF 4kB / 8kB ("low density") use the same die, but are tested differently
  - STM8S/AF 16kB / 32kB ("medium density") use the same die, but are tested differently
  - STM8S/AF 64kB / 128kB ("high density") use the same die, but are tested differently
  - for STM8L/AL I am not so sure about the actual dies usage

Having said that - and since I have no details about the "secret" device identifier you mentioned - I see no other way to detect the device type than checking if READ commands to certain addresses fail. Specifically:
  - check location of EEPROM for the family
  - check increasing Flash addresses for the the P-flash size

Of course the "problem" with this method is that I cannot distinguish between a 16kB and 32kB device, respectively a 64kB and 128kB, as the ROM-BL doesn't reject r/w/e access to the untested flash pages.

But again, as I see no other method to detect the device type without breaking a NDA, I will close this issue for now. If someone can come up with an idea I'm happy to re-open it again...?

Have a great day

**Closed as completed by gicking** 2021-01-09 20:27 UTC
